routes/web.php
<?php



/*просмотр сайтов клиента через поддомен*/
$domain = 'localhost';
Route::domain('{prefix}.'.$domain)->group(function () {
    $slug = '';
    $levelInclude = 5;
    for ($i = 1; $i <= $levelInclude; $i++)
        $slug .= '{slug'.$i.'?}/';
    // return Route::get($slug ,'Admin\OrderController@fake');

    Route::get($slug, function ($prefix){
        //найти страницу
        dd($prefix);
    });
});

/*просмотр сайта клиента через их домен*/
/*
Порядок действий:
    1) Определить prefix сайта и проверить на существование и активность в бд
    2) Определить какие slug заданы
*/
Route::get('/', 'MainController@index')->name('main.index');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// Route::resource('/construct-panel', 'Admin\Brunhilda\MainController');

Route::group(['prefix' => '/admin', 'middleware' => ['auth']], function (){
    Route::resource('/', 'Admin\Brunhilda\DashboardController');
    Route::group(['middleware' => ['can.show.tpl', 'is.admin']], function (){
        Route::resource('/tpl', 'Admin\Brunhilda\TplController');
        Route::resource('/tplType', 'Admin\Brunhilda\TplTypeController');
        Route::resource('/jsLib', 'Admin\Brunhilda\JsLibController');
        Route::resource('/cssLib', 'Admin\Brunhilda\CssLibController');
        Route::resource('/field', 'Admin\Brunhilda\FieldController');
    });
    Route::group(['middleware' => ['is.admin']], function (){
        Route::resource('/sites', 'Admin\Brunhilda\SiteController');
        Route::resource('/sites/{site}/pages', 'Admin\Brunhilda\PageController');
        Route::resource('/users', 'Admin\UserController');
        Route::resource('/roles', 'Admin\RoleController');
        Route::resource('/accounts', 'Admin\AccountController');
    });
});

Route::get('/construct/{any?}', 'Admin\Brunhilda\SpaController@index')->where('any', '.*')->name('construct')->middleware(['auth' /*'can.show.visual.construct',*/]);







/*можно потом удалить*/

// Route::get('fake', 'Admin\OrderController@fake')->name('fake');


//если есть роут в таблице pages, то включить его
// \App\Services\UserRoutesService::routes();

app/Tpl.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Tpl extends Model implements HasMediaConversions
{
    use HasMediaTrait;


    protected $table = 'tpls';
    public $timestamps = false;
    protected $guarded = [];

    // protected $hidden = ['id', 'name'];
    protected $visible = ['id', 'name', 'img'];

    public function tplType()
    {
        return $this->belongsTo('App\TplType', 'type_id', 'id');
    }

    public function fields()
    {
        return $this->hasMany('App\Field');
    }

    public function blockFields()
    {
        return $this->hasMany('App\BlockField');
    }

    public function blocks()
    {
        return $this->hasMany('App\Block');
    }






    /*************РАБОТА С ИЗОБРАЖЕНИЯМИ***************/
    public function registerMediaConversions(Media $media = null)
    {
        //изображения для превью
        $this->addMediaConversion('preview')
              ->width(640)
              ->height(330)
              ->sharpen(10);
    }



    /***********************************CUSTOM FUNCTION******************************************/

    /*выполняет запрос на выборку конкретного шаблона с его филдами*/
    public static function getTpl($tpl_id)
    {
        return self::where('id', $tpl_id)
                    ->with('fields')
                    ->get()
                    ->first();
    }
}

app/TplType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;

class TplType extends Model
{
    protected $table = 'tpl_types';
    public $timestamps = false;
    protected $guarded = [];



    /*********************************RELATIONSHIP********************************/
    public function tpls()
    {
        return $this->hasMany('App\Tpl', 'type_id', 'id');
    }





    /***********************************CUSTOM FUNCTIONS*****************************************/

    /*возвращает типы и шаблоны*/
    public static function getTypesWithTemplates()
    {
        $types = TplType::with('tpls')->get();
        foreach ($types as &$type)
        {
            $type['active'] = false;
            foreach ($type->tpls as &$tpl)
                $tpl['img'] = ($tpl->preview)? URL::to('/').$tpl->preview: URL::to('/')."/images/imageNotFound.jpg";
        }
        return $types;
    }



}

app/Http/Controllers/Admin/Brunhilda/TplController.php
<?php

namespace App\Http\Controllers\Admin\Brunhilda;

use App\CssLib;
use App\Field;
use App\Http\Controllers\Controller;
use App\JsLib;
use App\Tpl;
use App\TplType;
use Illuminate\Http\Request;

class TplController extends Controller
{


                        // if (isset($n->getMedia('news')[0])) {
                        //     echo URL::to('/').$n->getMedia('news')[0]->getUrl('indexAnons');
                        // } else {
                        //     echo "/images/imageNotFound.jpg";
                        // }


    /**
     * отображение всех шаблонов
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /*
        извлечь шаблон из бд
        извлчь все его переменные
        сформировать в один массив все переменные
        отрендерить
        */
        // $tpl = Tpl::find(1);
        // $replace = [];
        // $search = [];
        // foreach ($tpl->fields as $field)
        // {
        //     // dd('{{ $'.$field->name.' }}');
        //     $search[] = '{{ $'.$field->name.' }}';
        //     $replace[] = $field->{'var_'.$field->type};
        // }
        // echo $html = str_replace($search, $replace, $tpl->html);

        $tpls = Tpl::all();
        return view('admin.construct.tpl.index', compact('tpls'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tplTypes = TplType::all();
        $jsLibs = JsLib::all();
        $cssLibs = CssLib::all();
        return view('admin.construct.tpl.create', compact('tplTypes', 'jsLibs', 'cssLibs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|string',
            'css' => 'nullable|string',
            'html' => 'nullable|string',
            'js' => 'nullable|string',
            'type_id' => 'required|integer|min:1',
            'js_libs.*' => 'nullable|integer',
            'css_libs.*' => 'nullable|integer',
        ]);
        //получение адресов библиотек js
        $data['js_libs'] = json_encode(JsLib::whereIn('id', $request->js_libs ?? [])->pluck('url'));
        $data['css_libs'] = json_encode(CssLib::whereIn('id', $request->css_libs ?? [])->pluck('url'));

        $tpl = Tpl::create($data);
        //создание обязательных переменных
        Field::createDataField($tpl);

        //загрузка превью
        if ($tpl && $request->hasFile('preview')) {
            $tpl->addMedia($request->preview)->toMediaCollection('preview');
            $linkImage = $tpl->getMedia('preview')->first()->getUrl('preview');
            $tpl->preview = parse_url($linkImage)['path'];
            $tpl->save();
        }

        return redirect()->route('tpl.edit', $tpl->id)->with('flash_message', 'Шаблон создан.');
    }

    public function edit(Tpl $tpl)
    {
        $tplTypes = TplType::all();
        $jsLibs = JsLib::all();
        $cssLibs = CssLib::all();
        return view('admin.construct.tpl.edit', compact('tpl', 'tplTypes', 'jsLibs', 'cssLibs'));
    }

    public function update(Request $request, Tpl $tpl)
    {

        $data = $request->validate([
            'name' => 'nullable|string',
            'css' => 'nullable|string',
            'html' => 'nullable|string',
            'js' => 'nullable|string',
            'type_id' => 'nullable|integer|min:1',
            'js_libs.*' => 'nullable|integer',
            'css_libs.*' => 'nullable|integer',
        ]);
        $data['js_libs'] = json_encode(JsLib::whereIn('id', $request->js_libs ?? [])->pluck('url'));
        $data['css_libs'] = json_encode(CssLib::whereIn('id', $request->css_libs ?? [])->pluck('url'));
        $result = $tpl->update($data);

        return back()->with('flash_message', 'Изменения сохранены.');
    }

    public function __construct()
    {
        $this->middleware('can.create.tpl')->only(['create', 'store']);
        $this->middleware('can.edit.tpl')->only(['edit', 'update']);
        $this->middleware('can.remove.tpl')->only(['destroy']);
    }

}

resources/views/admin/construct/tpl/create.blade.php
@extends('admin.layouts.app')

@push('stylesheets')
    <link rel="stylesheet" href="/vendors/multi-select/css/multi-select.css">
@endpush

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.jslibs').multiSelect({
              selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Список js-модулей'>",
              selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Подключенные js-модули'>",
              afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function(e){
                  if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                  }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function(e){
                  if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                  }
                });
              },
              afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
              },
              afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
              }
            });
            $('.csslibs').multiSelect({
              selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Список css-модулей'>",
              selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Подключенные css-модули'>",
              afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function(e){
                  if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                  }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function(e){
                  if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                  }
                });
              },
              afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
              },
              afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
              }
            });
        });
    </script>

    <script src="/vendors/multi-select/js/jquery.quicksearch.js"></script>
    <script src="/vendors/multi-select/js/jquery.multi-select.js"></script>
@endpush

@section('content')
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        <form action="{{ route('tpl.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="col-md-6 col-sm-12 col-xs-12">
                <textarea class="form-control search" name="name" id="" cols="30" rows="10" placeholder="Название">{{ old('name') }}</textarea>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
                <textarea class="form-control search" name="html" id="" cols="30" rows="10" placeholder="HTML">{{ old('html') }}</textarea>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
                <textarea class="form-control search" name="css" id="" cols="30" rows="10" placeholder="CSS">{{ old('css') }}</textarea>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
                <textarea class="form-control search" name="js" id="" cols="30" rows="10" placeholder="JS">{{ old('js') }}</textarea>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control search" name="type_id">
                    @foreach ($tplTypes as $type)
                        <option  value="{{ $type->id }}">{{ $type->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input class="search" type="file" name="preview">
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="item form-group">
                    <select class="jslibs" id='custom-headers' multiple='multiple' name='js_libs[]'>
                        @foreach ($jsLibs as $jsLib)
                            <option value="{{ $jsLib->id }}">{{ $jsLib->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="item form-group">
                    <select class="csslibs" id='custom-headers' multiple='multiple' name='css_libs[]'>
                        @foreach ($cssLibs as $cssLib)
                            <option value="{{ $cssLib->id }}">{{ $cssLib->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button class="btn btn-success" type="submit">Создать</button>
            </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/construct/tpl/edit.blade.php
@extends('admin.layouts.app')

@push('stylesheets')
    <link rel="stylesheet" href="/vendors/multi-select/css/multi-select.css">
@endpush


@push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.jslibs').multiSelect({
              selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Список js-модулей'>",
              selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Подключенные js-модули'>",
              afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function(e){
                  if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                  }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function(e){
                  if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                  }
                });
              },
              afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
              },
              afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
              }
            });
            $('.csslibs').multiSelect({
              selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Список css-модулей'>",
              selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Подключенные css-модули'>",
              afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function(e){
                  if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                  }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function(e){
                  if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                  }
                });
              },
              afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
              },
              afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
              }
            });
        });
    </script>

    <script src="/vendors/multi-select/js/jquery.quicksearch.js"></script>
    <script src="/vendors/multi-select/js/jquery.multi-select.js"></script>
@endpush

@section('content')
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="" role="tabpanel" data-example-id="togglable-tabs">

          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active">
              <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Основное</a>
            </li>
            <li role="presentation" class="">
              <a href="#tab_content2" id="profile-tab2" role="tab" data-toggle="tab" aria-expanded="false">HTML</a>
            </li>
            <li role="presentation" class="">
              <a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">CSS</a>
            </li>
            <li role="presentation" class="">
              <a href="#tab_content4" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">JS</a>
            </li>
            <li role="presentation" class="">
              <a href="#tab_content5" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">JS-модули</a>
            </li>
            <li role="presentation" class="">
              <a href="#tab_content6" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">CSS-модули</a>
            </li>
          </ul>
          <div id="myTabContent" class="tab-content">

            <form action="{{ route('tpl.update', $tpl) }}" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{ method_field('PATCH') }}



              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>

                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input class="form-control search" type="text" name="name" placeholder="Название" value="{{ $tpl->name }}">
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control search" name="type_id">
                        @foreach ($tplTypes as $type)
                            <option
                                @if ($type->id == $tpl->type_id)
                                     {{ 'selected' }}
                                 @endif
                                value="{{ $type->id }}">{{ $type->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <input class="search" type="file">
                </div>
              </div>



              <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <textarea class="form-control search" name="html" cols="30" rows="30" placeholder="HTML">{{ $tpl->html }}</textarea>
                </div>
              </div>


              <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <textarea class="form-control search" name="css" cols="30" rows="30" placeholder="CSS">{{ $tpl->css }}</textarea>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <textarea class="form-control search" name="js" cols="30" rows="30" placeholder="JS">{{ $tpl->js }}</textarea>
                </div>
              </div>


              <div role="tabpanel" class="tab-pane fade" id="tab_content5" aria-labelledby="profile-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <?php
                    $js_libs = json_decode($tpl->js_libs) ?? [];
                    // dd($js_libs);
                  ?>
                    <div class="item form-group">
                        <select class="jslibs" id='custom-headers' multiple='multiple' name='js_libs[]'>
                            @foreach ($jsLibs ?? [] as $jsLib)
                                <option <?php if (in_array($jsLib->url, $js_libs)) echo 'selected'; ?> value="{{ $jsLib->id }}">{{ $jsLib->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
              </div>


              <div role="tabpanel" class="tab-pane fade" id="tab_content6" aria-labelledby="profile-tab">
                <div class="col-md-2 col-sm-2 col-xs-12">
                  <a class="btn btn-success form-control" href="{{ route('tpl.index') }}">Назад</a>
                </div>
                <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                    <button class="btn btn-success form-control" type="submit">Сохранить</button>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <?php
                    $css_libs = json_decode($tpl->css_libs) ?? [];
                  ?>
                    <div class="item form-group">
                        <select class="csslibs" id='custom-headers' multiple='multiple' name='css_libs[]'>

                            @foreach ($cssLibs ?? [] as $cssLib)
                                <option <?php if (in_array($cssLib->url, $css_libs)) echo 'selected'; ?> value="{{ $cssLib->id }}">{{ $cssLib->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
              </div>



            </form>
          </div>
        </div>
        @foreach ($tpl->fields as $field)
        @if ($field->removable)
          <div class="row">
            <form action="{{ route('field.destroy', $field) }}" method="post">
              {{ csrf_field() }}
              {{ method_field('DELETE') }}
              <div class="col-md-3 col-md-offset-1">
                <h4>
                  {{ $field->type }} {{ $field->name }} = {{ $field->{('var_'.$field->type)} }}
                </h4>
              </div>
              <button class="btn btn-danger">Удалить</button>
            </form>
          </div>
        @endif


        @endforeach
        <form action="{{ route('field.store', ['tpl_id' => $tpl->id]) }}" method="post">
          {{ csrf_field() }}
          <div class="col-md-2 col-sm-2 col-xs-12">
            <select class="form-control search" name="type" placeholder="Тип данных">
              <option value="char">char</option>
              <option value="text">text</option>
              <option value="int">int</option>
            </select>
          </div>
          <div class="col-md-2 col-sm-2 col-xs-12">
            <input class="form-control search" type="text" name="name" placeholder="Имя переменной">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <input class="form-control search" type="text" name="value" placeholder="Значение по-умолчанию">
          </div>
          <div class="col-md-2 col-sm-2 col-xs-12">
            <button class="form-control btn btn-success" type="submit">Добавить</button>
          </div>
        </form>



        <div class="col-md-12 col-sm-12 col-xs-12">
          <form action="{{ route('field.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="name" value="data">
            <input type="hidden" name="type" value="data">
            <input type="hidden" name="tpl_id" value="{{ $tpl->id }}">
            <input type="file" multiple="multiple" name="value[]" accept="image/*">
            <button class="btn btn-success" type="submit">Добавить</button>
          </form>
        </div>

      </div>
    </div>
  </div>
@endsection

resources/views/admin/construct/tpl/index.blade.php
@extends('admin.layouts.app')

@section('content')
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        @can('create-tpl')
          <a class="btn btn-success" href="{{ route('tpl.create') }}">Новый шаблон</a>
        @endcan
        <br>
        <?php $i=1; ?>
        @foreach ($tpls as $tpl)
            <?php echo $i++?>
            {{ $tpl->name }}
            @can('edit-tpl')
              <a class="btn btn-success btn-xs" href="{{ route('tpl.edit', $tpl) }}">Редактировать</a>
            @endcan
            <br>


            {{-- {{ dump($tpl) }} --}}
        @endforeach


      </div>
    </div>
  </div>
@endsection