routes/web.php
<?php



/*просмотр сайтов клиента через поддомен*/
$domain = 'localhost';
Route::domain('{prefix}.'.$domain)->group(function () {
    $slug = '';
    $levelInclude = 5;
    for ($i = 1; $i <= $levelInclude; $i++)
        $slug .= '{slug'.$i.'?}/';
    // return Route::get($slug ,'Admin\OrderController@fake');

    Route::get($slug, function ($prefix){
        //найти страницу
        dd($prefix);
    });
});

/*просмотр сайта клиента через их домен*/
/*
Порядок действий:
    1) Определить prefix сайта и проверить на существование и активность в бд
    2) Определить какие slug заданы
*/
Route::get('/', 'MainController@index')->name('main.index');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// Route::resource('/construct-panel', 'Admin\Brunhilda\MainController');

Route::group(['prefix' => '/admin', 'middleware' => ['auth']], function (){
    Route::resource('/', 'Admin\Brunhilda\DashboardController');
    Route::group(['middleware' => ['can.show.tpl', 'is.admin']], function (){
        Route::resource('/tpl', 'Admin\Brunhilda\TplController');
        Route::resource('/tplType', 'Admin\Brunhilda\TplTypeController');
        Route::resource('/jsLib', 'Admin\Brunhilda\JsLibController');
        Route::resource('/cssLib', 'Admin\Brunhilda\CssLibController');
        Route::resource('/field', 'Admin\Brunhilda\FieldController');
    });
    Route::group(['middleware' => ['is.admin']], function (){
        Route::resource('/sites', 'Admin\Brunhilda\SiteController');
        Route::resource('/sites/{site}/pages', 'Admin\Brunhilda\PageController');
        Route::resource('/users', 'Admin\UserController');
        Route::resource('/roles', 'Admin\RoleController');
        Route::resource('/accounts', 'Admin\AccountController');
    });
});

Route::get('/construct/{any?}', 'Admin\Brunhilda\SpaController@index')->where('any', '.*')->name('construct')->middleware(['auth' /*'can.show.visual.construct',*/]);







/*можно потом удалить*/

// Route::get('fake', 'Admin\OrderController@fake')->name('fake');


//если есть роут в таблице pages, то включить его
// \App\Services\UserRoutesService::routes();

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Отображает весь список прав и ролей
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //получить роли с их правами
        $roles = Role::all();
        $permissions = Permission::all();
        return view('admin.userManagment.roles.index', compact('roles', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = RoleValidation::store($request);
        switch ($request->name) {
            case 'role':
                Role::create(['name' => $request->role]);
                break;
            case 'permission':
                Permission::create(['name' => $request->permission]);
                break;
        }
        return back()->with('flash_message', 'Успешно добавлено.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $role = Role::where('id', $id)->with('permissions')->get()->first();
        // $permissions = Permission::all();
        // return view('admin.userManagment.roles.show', compact('role', 'permissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->name ?? [];
        Role::find($id)->syncPermissions($data);
        return back()->with('flash_message', 'Изменения сохранены');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        switch ($request->name) {
            case 'role':
                Role::find($id)->delete();
                $message = "Роль была удалена.";
                break;
            case 'permission':
                Permission::find($id)->delete();
                $message = "Право было удалено.";
                break;
        }
        return redirect()->route('roles.index')->with('flash_message', $message);
    }
}

resources/views/admin/userManagment/roles/index.blade.php
@extends('admin.layouts.app')

@section('content')
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><i class="fa fa-bars"></i> Управление Ролями и Правами </h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Роли</a>
                        </li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Права</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <form action="" method="post">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="name" value="role">
                                    <div class="row">
                                        <div class="col-md-10 col-sm-10 col-xs-12">
                                            <input class="form-control search" type="text" placeholder="Название роли" name="role">
                                        </div>
                                        <div class="col-md-2 col-sm-2 col-xs-12">
                                            <button class="btn btn-success form-control" type="submit">Добавить</button>
                                        </div>
                                    </div>
                                </form>
                                <h3 class="page-header">Список ролей:</h3>
                            </div>
                            @foreach ($roles as $role)
                                <div>
                                    <div class="row">
                                        <div class="col-md-5 col-sm-5 col-xs-12">
                                            <h4><ul>{{ $role->name }}</ul></h4>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <form action="{{ route('roles.store') }}" method="post">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="name" value="permission">
                                    <div class="row">
                                        <div class="col-md-10 col-sm-10 col-xs-12">
                                            <input class="form-control search" type="text" placeholder="Название права" name="permission">
                                        </div>
                                        <div class="col-md-2 col-sm-2 col-xs-12">
                                            <button class="btn btn-success form-control" type="submit">Добавить</button>
                                        </div>
                                    </div>
                                </form>
                                <h3 class="page-header">Список прав:</h3>
                            </div>

                            <div class="row">
                                <div class="col-md-5 col-sm-5 col-xs-12">
                                    <ul>
                                        @foreach ($permissions as $permission)
                                            <li><h4>{{ $permission->name }}</h4></li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

@endsection

resources/views/admin/userManagment/roles/show.blade.php
@extends('admin.layouts.app')

@push('stylesheets')
    <link rel="stylesheet" href="/vendors/multi-select/css/multi-select.css">
@endpush

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.permissions').multiSelect({
              selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Список всех прав'>",
              selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Права текщей роли'>",
              afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function(e){
                  if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                  }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function(e){
                  if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                  }
                });
              },
              afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
              },
              afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
              }
            });
        });
    </script>

    <script src="/vendors/multi-select/js/jquery.quicksearch.js"></script>
    <script src="/vendors/multi-select/js/jquery.multi-select.js"></script>
@endpush

@section('content')
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <h3 class="page-header">Настрока роли "{{ $role->name }}":</h3>
        </div>
        <form action="{{ route('roles.update', $role) }}" method="post">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="item form-group">
                    <select class="permissions" id='custom-headers' multiple='multiple' name='name[]'>
                        @php
                            $arPermissions = array_pluck($role->permissions->toArray(), 'name');
                        @endphp
                        @foreach ($permissions as $permission)
                            @if (in_array($permission->name, $arPermissions))
                                <option selected value="{{ $permission->name }}">{{ $permission->name }}</option>
                            @else
                                <option value="{{ $permission->name }}">{{ $permission->name }}</option>
                            @endif

                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
                <a class="btn btn-success form-control" href="{{ route('roles.index') }}">Назад</a>
            </div>
            <div class="col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-8 col-xs-12">
                <button class="btn btn-success form-control" type="submit">Сохранить</button>
            </div>
        </form>

      </div>
    </div>
  </div>
@endsection