routes/web.php
<?php



/*просмотр сайтов клиента через поддомен*/
$domain = 'localhost';
Route::domain('{prefix}.'.$domain)->group(function () {
    $slug = '';
    $levelInclude = 5;
    for ($i = 1; $i <= $levelInclude; $i++)
        $slug .= '{slug'.$i.'?}/';
    // return Route::get($slug ,'Admin\OrderController@fake');

    Route::get($slug, function ($prefix){
        //найти страницу
        dd($prefix);
    });
});

/*просмотр сайта клиента через их домен*/
/*
Порядок действий:
    1) Определить prefix сайта и проверить на существование и активность в бд
    2) Определить какие slug заданы
*/
Route::get('/', 'MainController@index')->name('main.index');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// Route::resource('/construct-panel', 'Admin\Brunhilda\MainController');

Route::group(['prefix' => '/admin', 'middleware' => ['auth']], function (){
    Route::resource('/', 'Admin\Brunhilda\DashboardController');
    Route::group(['middleware' => ['can.show.tpl', 'is.admin']], function (){
        Route::resource('/tpl', 'Admin\Brunhilda\TplController');
        Route::resource('/tplType', 'Admin\Brunhilda\TplTypeController');
        Route::resource('/jsLib', 'Admin\Brunhilda\JsLibController');
        Route::resource('/cssLib', 'Admin\Brunhilda\CssLibController');
        Route::resource('/field', 'Admin\Brunhilda\FieldController');
    });
    Route::group(['middleware' => ['is.admin']], function (){
        Route::resource('/sites', 'Admin\Brunhilda\SiteController');
        Route::resource('/sites/{site}/pages', 'Admin\Brunhilda\PageController');
        Route::resource('/users', 'Admin\UserController');
        Route::resource('/roles', 'Admin\RoleController');
        Route::resource('/accounts', 'Admin\AccountController');
    });
});

Route::get('/construct/{any?}', 'Admin\Brunhilda\SpaController@index')->where('any', '.*')->name('construct')->middleware(['auth' /*'can.show.visual.construct',*/]);







/*можно потом удалить*/

// Route::get('fake', 'Admin\OrderController@fake')->name('fake');


//если есть роут в таблице pages, то включить его
// \App\Services\UserRoutesService::routes();

resources/views/admin/includes/footer.blade.php
        <!-- footer content -->
        <footer>
          <div class="pull-right">

          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>


    <script src="/vendors/moment/min/moment.min.js"></script>
    <script src="/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>


    @stack('scripts')

    <script src="{{ "/js/admin.js" }}"></script>
  </body>
</html>

resources/views/admin/includes/header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title')</title>

    <!-- Bootstrap -->
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    @stack('stylesheets')
    <!-- Custom Theme Style -->
    <link href="{{ "/css/admin.css" }}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            @include('admin.includes.menu')
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
{{--                     <img src=
                      @php
                          if (isset(Auth::user()->getMedia('avatar')[0]))
                          {
                              echo URL::to('/').Auth::user()->getMedia('avatar')[0]->getUrl('small');
                          }else{
                              echo '/images/avatarByDefault.jpg';
                          }
                      @endphp
                    alt="">{{ Illuminate\Support\Facades\Auth::user()->name }} --}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    {{-- <li><a href="{{ route('users.show', Auth::user()) }}"> Профиль</a></li> --}}
                    {{-- <li><a href="{{ route('personal.index') }}"> Публичный профиль</a></li> --}}
                    <li>
                      <a href="/logout" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i>
                        Log Out
                      </a> <form id="logout-form" action="/logout" method="POST" style="display: none;">{{ csrf_field() }}</form></li>
                  </ul>
                </li>

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

resources/views/admin/includes/menu.blade.php
<div class="navbar nav_title" style="border: 0;">
    <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>Brunhilda panel</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
    <div class="profile_pic">
{{--         <a href="{{ route('users.show', Auth::id()) }}">
            <img src=
                @php
                    if (isset(Auth::user()->getMedia('avatar')[0]))
                    {
                        echo URL::to('/').Auth::user()->getMedia('avatar')[0]->getUrl('small');
                    }else{
                        echo '/images/avatarByDefault.jpg';
                    }
                @endphp
             alt="..." class="img-circle profile_img">
        </a> --}}
    </div>
    <div class="profile_info">
        <span>Здравствуйте,</span>
        {{-- <h2>{{ Illuminate\Support\Facades\Auth::user()->name }}</h2> --}}
    </div>
    <div class="clearfix"></div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>Основное</h3>
        <ul class="nav side-menu">
            @hasanyrole('admin|tpl-developer')
                <li><a><i class="fa fa-shopping-cart"></i>Конструктор<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{ route('tpl.index') }}">Шаблоны</a></li>
                        <li><a href="{{ route('tplType.index') }}">Типы шаблонов</a></li>
                        <li><a href="{{ route('jsLib.index') }}">JS-модули</a></li>
                        <li><a href="{{ route('cssLib.index') }}">CSS-модули</a></li>
                        @role('admin')
                            <li><a href="{{ route('sites.index') }}">Сайты</a></li>
                        @endrole
                    </ul>
                </li>
            @endhasanyrole

            @role('admin')
                <li><a><i class="fa fa-shopping-cart"></i>Управление пользователями<span class="fa fa-chevron-down"></span>
                    <ul class="nav child_menu">
                        <li><a href="{{ route('users.index') }}">Пользователи</a></li>
                        <li><a href="{{ route('accounts.index') }}">Аккаунты</a></li>
                        <li><a href="{{ route('roles.index') }}">Роли и права</a></li>
                    </ul>
                </li>
            @endrole

            @hasanyrole('admin|tpl-developer|user')
                <li><a href="{{ route('construct') }}"><i class="fa fa-home"></i>Визуальный конструктор</a></li>
            @endhasanyrole
        </ul>
    </div>


</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ route('logout') }}">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<!-- /menu footer buttons -->